# This file defines the schema for GridSpray config
# @package _group_
_target_: benchmarl.environments.gridsworld.common.GridSprayConfig

grid_size: ???  # Required
num_agents: ???  # Required
spray_capacity: ???  # Required
max_steps: ???  # Required
coverage_size: ???